import { expect, test } from "@playwright/test";
import dotenv from "dotenv";
import BlaiseApiClient, { NewUser } from "blaise-api-node-client";
import { deleteTestUser, setupTestUser } from "./helpers/BlaiseHelpers";
import { loginToMir } from "./helpers/MirHelpers";
import axios from 'axios';
import { GoogleAuth } from 'google-auth-library';

if (process.env.NODE_ENV !== "production") {
    dotenv.config({ path: `${__dirname}/../../.env` });
}

const restApiUrl = process.env.REST_API_URL || "http://localhost:1337";
const questionnaireName = process.env.TEST_QUESTIONNAIRE;
const serverPark = process.env.SERVER_PARK;

const httpClient = axios.create();
let authorizationHeader: string = "";

// This is the IIFE pattern
(async () => {
  try {
    let authorizationHeader = await getIapToken("1034983553529-gapl7ndqce23gdtra82lc8di67eql2vl.apps.googleusercontent.com");

    console.log("Successfully retrieved tokenHeader:");
    console.log(authorizationHeader);
  } catch (error) {
    console.error("An error occurred in the main execution block:", error);
  }
})(); // The () at the end runs the function immediately



// BENTODO: Going to generate IAP_TOKEN here to test if wrong one is being sent through
if (!authorizationHeader) {
    console.warn('No IAP_TOKEN found in environment - generating a new one for testing');
    authorizationHeader = 'test-generated-iap-token';
}
else {
    console.log('IAP_TOKEN generated by BENTODO Call');
    console.log('IAP Token is '+ authorizationHeader.substring(0, 20) + '...' + authorizationHeader.substring(authorizationHeader.length - 10)); // Log only the beginning and end for security
}

if (authorizationHeader) {
    // BENTODO: do not checckin this log in future - security risk
    console.log('IAP Token is '+ authorizationHeader.substring(0, 10) + '...' + authorizationHeader.substring(authorizationHeader.length - 10)); // Log only the beginning and end for security
    console.log('Using pre-generated IAP token from environment');
    httpClient.interceptors.request.use((config) => {
        config.headers['Authorization'] = `${authorizationHeader}`;
        return config;
    });
} else {
    console.warn('No IAP_TOKEN found in environment - requests may fail');
}

const blaiseApiClient = new BlaiseApiClient(restApiUrl);
blaiseApiClient.httpClient = httpClient;

let userCredentials: NewUser;

if (!questionnaireName) {
    console.error("Questionnaire name is undefined");
    process.exit(1);
}

if (!serverPark) {
    console.error("Server park is undefined");
    process.exit(1);
}

test.describe("ARPR without data", () => {
    test.beforeEach(async ({ page }, testInfo) => {
        console.log(`Started running before each hook for test ${testInfo.title}`);
        testInfo.setTimeout(30000);
        userCredentials = await setupTestUser(blaiseApiClient, serverPark);
        console.log(`Finished running before each hook for test ${testInfo.title}`);
    });
    test.afterEach(async ({ page }, testInfo) => {
        console.log(`Started running after each hook for test ${testInfo.title}`);
        await deleteTestUser(blaiseApiClient, serverPark, userCredentials.name);
        console.log(`Finished running after each hook for test ${testInfo.title}`);
    });
    test("ARPR without data", async ({ page }, testInfo) => {
        console.log(`Started running ${testInfo.title}`);
        await loginToMir(page, userCredentials);
        await page.click("text=Appointment resource planning");
        await expect(page.locator("h1")).toHaveText("Run appointment resource planning report");
        await expect(page.locator(".ons-panel__body ").nth(0)).toContainText("Run a Daybatch first to obtain the most accurate results.");
        await expect(page.locator(".ons-panel__body ").nth(0)).toContainText("Appointments that have already been attempted will not be displayed.");
        await page.locator("#Date").type("30-06-1990");
        await page.click("button[type=submit]");
        await page.waitForSelector("text=Loading", { state: "hidden" });
        await expect(page.locator(".ons-panel__body ").nth(1)).toContainText("No questionnaires found for given parameters.");        
        console.log(`Finished running ${testInfo.title}`);
    });
});

async function getIapToken(audience: string): Promise<string> {
  const auth = new GoogleAuth();
  try {
    // 1. Get the client that can fetch ID tokens
    const idTokenClient = await auth.getIdTokenClient(audience);
    
    // 2. Use the client to get the headers, which contain the token
    const headers = await idTokenClient.getRequestHeaders();
    
    return headers.Authorization; // This is the 'Bearer <token>' string

  } catch (error) {
    console.error('Error getting IAP token:', error);
    throw new Error('Could not generate IAP token.');
  }
}

/*
commenting this test out for now, for some reason the cati book appointment page displays differently when run from a concourse worker
ideally we want to upgrade to a version of blaise that allows appointments to be booked via the api

import { deleteTestUser, setupQuestionnaire, setupTestUser, uninstallQuestionnaire } from "./helpers/BlaiseHelpers";
import { setupAppointment, clearCatiData } from "./helpers/CatiHelpers";
import { loginToMir, createDateForTomorrow } from "./helpers/MirHelpers";

test.describe("ARPR with data", () => {
    test.beforeEach(async ({ page }, testInfo) => {
        console.log(`Started running before each hook for test ${testInfo.title}`);
        testInfo.setTimeout(180000);
        userCredentials = await setupTestUser(blaiseApiClient, serverPark);
        await setupQuestionnaire(blaiseApiClient, questionnaireName, serverPark);
        await setupAppointment(page, questionnaireName, userCredentials);
        console.log(`Finished running before each hook for test ${testInfo.title}`);
    });
    test.afterEach(async ({ page }, testInfo) => {
        console.log(`Started running after each hook for test ${testInfo.title}`);
        await deleteTestUser(blaiseApiClient, serverPark, userCredentials.name);
        await clearCatiData(page, questionnaireName, userCredentials);
        await uninstallQuestionnaire(blaiseApiClient, serverPark, questionnaireName);
        console.log(`Finished running after each hook for test ${testInfo.title}`);
    });
    test("ARPR with data", async ({ page }, testInfo) => {
        console.log(`Started running ${testInfo.title}`);
        await loginToMir(page, userCredentials);
        await page.click("text=Appointment resource planning");
        await expect(page.locator("h1")).toHaveText("Run appointment resource planning report");
        await expect(page.locator(".ons-panel__body ").nth(0)).toContainText("Run a Daybatch first to obtain the most accurate results.");
        await expect(page.locator(".ons-panel__body ").nth(0)).toContainText("Appointments that have already been attempted will not be displayed.");
        await page.locator("#Date").type(`${createDateForTomorrow()}`);
        await page.click("button[type=submit]");
        await page.click('button:has-text("Select All")');
        await page.click('button:has-text("Run report")');
        await page.waitForSelector("text=Loading", { state: "hidden" });
        const row = await page.locator(`tr:has-text('${questionnaireName}')`);
        await expect(row.locator('td:nth-child(2)')).toHaveText("10:00");
        await expect(row.locator('td:nth-child(3)')).toHaveText("English");
        await expect(row.locator('td:nth-child(4)')).toHaveText("1");
        console.log(`Finished running ${testInfo.title}`);
    });
});
*/
